<?php
echo "    <div class=\"site-section bg-primary py-5\">\n";
echo "      <div class=\"container\">\n";
echo "        <div class=\"row align-items-center\">\n";
echo "          <div class=\"col-lg-7 mb-4 mb-md-0\">\n";
echo "            <h2 class=\"mb-0 text-white\">What are you waiting for?</h2>\n";
echo "            <p class=\"mb-0 opa-7\">Let's buy bus ticket from us.</p>\n";
echo "          </div>\n";
echo "          <div class=\"col-lg-5 text-md-right\">\n";
echo "            <a href=\"purchase.php\" class=\"btn btn-primary btn-white\">Buy ticket now</a>\n";
echo "          </div>\n";
echo "        </div>\n";
echo "      </div>\n";
echo "    </div>\n";
echo "\n";
echo "      \n";
echo "      <footer class=\"site-footer\" style='background-color:white;'>\n";
echo "        <div class=\"container\">\n";
echo "          <div class=\"row\">\n";
echo "            <div class=\"col-lg-3\">\n";
echo "              <h2 class=\"footer-heading mb-4\">About Us</h2>\n";
echo "              <p>We wish Malaysians can rely more on public transport like bus. Car pooling is a very good way to support green environment.</p>\n";
echo "              <ul class=\"list-unstyled social\">\n";
echo "                <li><a href=\"#\"><span class=\"icon-facebook\"></span></a></li>\n";
echo "                <li><a href=\"#\"><span class=\"icon-instagram\"></span></a></li>\n";
echo "                <li><a href=\"#\"><span class=\"icon-twitter\"></span></a></li>\n";
echo "                <li><a href=\"#\"><span class=\"icon-linkedin\"></span></a></li>\n";
echo "              </ul>\n";
echo "            </div>\n";
echo "            <div class=\"col-lg-8 ml-auto\">\n";
echo "              <div class=\"row\">\n";
echo "                <div class=\"col-lg-3\">\n";
echo "                  <h2 class=\"footer-heading mb-4\">Quick Links</h2>\n";
echo "                  <ul class=\"list-unstyled\">\n";
echo "                    <li><a href=\"index.php\">Home</a></li>\n";
echo "                    <li><a href=\"about.php\">About Us</a></li>\n";
echo "                    <li><a href=\"purchase.php\">Purchase</a></li>\n";
echo "                    <li><a href=\"listing.php\">Listing</a></li>\n";
echo "                    <li><a href=\"contact.php\">Contact Us</a></li>\n";
echo "                    <li><a href=\"setting.php\">Setting</a></li>\n";
echo "                  </ul>\n";
echo "                </div>\n";
echo "                <div class=\"col-lg-3\">\n";
echo "                  <h2 class=\"footer-heading mb-4\">Resources</h2>\n";
echo "                  <ul class=\"list-unstyled\">\n";
echo "                    <li><a href=\"index.php\">Home</a></li>\n";
echo "                    <li><a href=\"purchase.php\">Purchase</a></li>\n";
echo "                    <li><a href=\"listing.php\">Listing</a></li>\n";

echo "                  </ul>\n";
echo "                </div>\n";
echo "                <div class=\"col-lg-3\">\n";
echo "                  <h2 class=\"footer-heading mb-4\">Support</h2>\n";
echo "                  <ul class=\"list-unstyled\">\n";
echo "                    <li><a href=\"contact.php\">Contact Us</a></li>\n";
echo "                  </ul>\n";
echo "                </div>\n";
echo "                <div class=\"col-lg-3\">\n";
echo "                  <h2 class=\"footer-heading mb-4\">Company</h2>\n";
echo "                  <ul class=\"list-unstyled\">\n";
echo "                    <li><a href=\"about.php\">About Us</a></li>\n";
echo "                  </ul>\n";
echo "                </div>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "          <div class=\"row pt-5 mt-5 text-center\">\n";
echo "            <div class=\"col-md-12\">\n";
echo "              <div class=\"border-top pt-5\">\n";
echo "                <p>\n";
echo "              <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\n";
echo "              Copyright ©<script>document.write(new Date().getFullYear());</script> All rights reserved ";
echo "              <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\n";
echo "              </p>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "\n";
echo "          </div>\n";
echo "        </div>\n";
echo "      </footer>\n";
echo "\n";
echo "    </div>\n";
echo "\n";
echo "    <script src=\"js/jquery-3.3.1.min.js\"></script>\n";
echo "    <script src=\"js/popper.min.js\"></script>\n";
echo "    <script src=\"js/bootstrap.min.js\"></script>\n";
echo "    <script src=\"js/owl.carousel.min.js\"></script>\n";
echo "    <script src=\"js/jquery.sticky.js\"></script>\n";
echo "    <script src=\"js/jquery.waypoints.min.js\"></script>\n";
echo "    <script src=\"js/jquery.animateNumber.min.js\"></script>\n";
echo "    <script src=\"js/jquery.fancybox.min.js\"></script>\n";
echo "    <script src=\"js/jquery.easing.1.3.js\"></script>\n";
echo "    <script src=\"js/bootstrap-datepicker.min.js\"></script>\n";
echo "    <script src=\"js/aos.js\"></script>\n";
echo "\n";
echo "    <script src=\"js/main.js\"></script>\n";
echo "\n"; ?>