<?php
include("cookie.php");
print "<!doctype html>\n";
print "<html lang=\"en\">\n";
print "\n";
print "  <head>\n";
print "    <title>CarRental — Free Website Template by Colorlib</title>\n";
print "    <meta charset=\"utf-8\">\n";
print "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n";
print "\n";
print "    <link href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@400;700;900&display=swap\" rel=\"stylesheet\">\n";
print "\n";
print "    <link rel=\"stylesheet\" href=\"fonts/icomoon/style.css\">\n";
print "\n";
print "    <link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\n";
print "    <link rel=\"stylesheet\" href=\"css/bootstrap-datepicker.css\">\n";
print "    <link rel=\"stylesheet\" href=\"css/jquery.fancybox.min.css\">\n";
print "    <link rel=\"stylesheet\" href=\"css/owl.carousel.min.css\">\n";
print "    <link rel=\"stylesheet\" href=\"css/owl.theme.default.min.css\">\n";
print "    <link rel=\"stylesheet\" href=\"fonts/flaticon/font/flaticon.css\">\n";
print "    <link rel=\"stylesheet\" href=\"css/aos.css\">\n";
print "\n";
print "    <!-- MAIN CSS -->\n";
print "    <link rel=\"stylesheet\" href=\"css/style.css\">\n";
print "\n";
print "  </head>\n";
print "\n";
echo "<body style='background-color:$color;'>";
print "\n";
print "    \n";
print "    <div class=\"site-wrap\" id=\"home-section\">\n";
print "\n";
print "      <div class=\"site-mobile-menu site-navbar-target\">\n";
print "        <div class=\"site-mobile-menu-header\">\n";
print "          <div class=\"site-mobile-menu-close mt-3\">\n";
print "            <span class=\"icon-close2 js-menu-toggle\"></span>\n";
print "          </div>\n";
print "        </div>\n";
print "        <div class=\"site-mobile-menu-body\"></div>\n";
print "      </div>\n";
print "\n";
print "\n";
print "\n";
print "      <header class=\"site-navbar site-navbar-target\" role=\"banner\">\n";
print "\n";
print "        <div class=\"container\">\n";
print "          <div class=\"row align-items-center position-relative\">\n";
print "\n";
print "            <div class=\"col-3\">\n";
print "              <div class=\"site-logo\">\n";
print "                <a href=\"index.php\"><strong>Bus Ticket Online</strong></a>\n";
print "              </div>\n";
print "            </div>\n";
print "\n";
print "            <div class=\"col-9  text-right\">\n";
print "              \n";
print "              <span class=\"d-inline-block d-lg-none\"><a href=\"#\" class=\" site-menu-toggle js-menu-toggle py-5 \"><span class=\"icon-menu h3 text-black\"></span></a></span>\n";
print "\n";
print "              <nav class=\"site-navigation text-right ml-auto d-none d-lg-block\" role=\"navigation\">\n";
print "                <ul class=\"site-menu main-menu js-clone-nav ml-auto \">\n";
echo "					</br>";
echo "                  <li><a href=\"index.php\" class=\"nav-link\">Home</a></li>\n";
echo "                  <li><a href=\"purchase.php\" class=\"nav-link\">Purchase</a></li>\n";
echo "                  <li><a href=\"about.php\" class=\"nav-link\">About</a></li>\n";
echo "                  <li><a href=\"contact.php\" class=\"nav-link\">Contact</a></li>\n";
echo "                  <li><a href=\"register.php\" class=\"nav-link\">Register</a></li>\n";
echo "                  <li><a href=\"signIn.php\" class=\"nav-link\">Sign In</a></li>\n";
echo "                  <li><a href=\"cart.php\" class=\"nav-link\">Cart</a></li>\n";
echo "                  <li><a href=\"history.php\" class=\"nav-link\">Purchase History</a></li>\n";
echo "                  <li><a href=\"setting.php\" class=\"nav-link\">Setting</a></li>\n";
print "                </ul>\n";
print "              </nav>\n";
print                $country . " | " . $language . " | " . $currency;
print "            </div>\n";
print "\n";

	

print "            \n";
print "          </div>\n";
print "        </div>\n";
print "\n";
print "      </header>\n";
print "\n";
print "      \n";
print "      <div class=\"hero\" style=\"background-image: url('images/background.jpeg');\">\n";
print "        \n";
print "        <div class=\"container\">\n";
print "          <div class=\"row align-items-center justify-content-center\">\n";
print "            <div class=\"col-lg-10\">\n";
print "\n";
print "              <div class=\"row mb-5\">\n";
print "                <div class=\"col-lg-7 intro\">\n";