<?php
echo "<!doctype html>\n";
echo "<html lang=\"en\">\n";
echo "  <head>\n";
echo "   <title>CarRental &mdash; Free Website Template by Colorlib</title>\n";
echo "   <meta charset=\"utf-8\">\n";
echo "   <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n";
echo "    <link href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@400;700;900&display=swap\" rel=\"stylesheet\">\n";
echo "    <link rel=\"stylesheet\" href=\"fonts/icomoon/style.css\">\n";
echo "    <link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\n";
echo "   <link rel=\"stylesheet\" href=\"css/bootstrap-datepicker.css\">\n";
echo "   <link rel=\"stylesheet\" href=\"css/jquery.fancybox.min.css\">\n";
echo "   <link rel=\"stylesheet\" href=\"css/owl.carousel.min.css\">\n";
echo "   <link rel=\"stylesheet\" href=\"css/owl.theme.default.min.css\">\n";
echo "   <link rel=\"stylesheet\" href=\"fonts/flaticon/font/flaticon.css\">\n";
echo "   <link rel=\"stylesheet\" href=\"css/aos.css\">\n";
echo "    <!-- MAIN CSS -->\n";
echo "   <link rel=\"stylesheet\" href=\"css/style.css\">\n";
echo "  </head>\n";
echo "  <body>\n";
echo "    \n";
echo "   <div class=\"site-wrap\" id=\"home-section\">\n";
echo "      <div class=\"site-mobile-menu site-navbar-target\">\n";
echo "       <div class=\"site-mobile-menu-header\">\n";
echo "         <div class=\"site-mobile-menu-close mt-3\">\n";
echo "           <span class=\"icon-close2 js-menu-toggle\"></span>\n";
echo "         </div>\n";
echo "       </div>\n";
echo "       <div class=\"site-mobile-menu-body\"></div>\n";
echo "     </div>\n";
echo "\n";
echo "      <header class=\"site-navbar site-navbar-target\" role=\"banner\">\n";
echo "        <div class=\"container\">\n";
echo "         <div class=\"row align-items-center position-relative\">\n";
echo "            <div class=\"col-3\">\n";
echo "             <div class=\"site-logo\">\n";
echo "               <a href=\"index.php\"><strong>Bus Booking System</strong></a>\n";
echo "             </div>\n";
echo "           </div>\n";
echo "            <div class=\"col-9  text-right\">\n";
echo "             \n";
echo "             <span class=\"d-inline-block d-lg-none\"><a href=\"#\" class=\" site-menu-toggle js-menu-toggle py-5 \"><span class=\"icon-menu h3 text-black\"></span></a></span>\n";
echo "              <nav class=\"site-navigation text-right ml-auto d-none d-lg-block\" role=\"navigation\">\n";
echo "               <ul class=\"site-menu main-menu js-clone-nav ml-auto \">\n";
echo "                  <li><a href=\"index.php\" class=\"nav-link\">Home</a></li>\n";
echo "                  <li><a href=\"listing.php\" class=\"nav-link\">Listing</a></li>\n";
echo "                  <li><a href=\"testimonials.php\" class=\"nav-link\">Testimonials</a></li>\n";
echo "                  <li><a href=\"cart.php\" class=\"nav-link\">Cart</a></li>\n";
echo "                  <li><a href=\"history.php\" class=\"nav-link\">Purchase History</a></li>\n";
echo "                  <li class=\"active\"><a href=\"about.php\" class=\"nav-link\">About</a></li>\n";
echo "                  <li><a href=\"contact.php\" class=\"nav-link\">Contact</a></li>\n";
echo "                  <li><a href=\"register.php\" class=\"nav-link\">Register</a></li>\n";
echo "                  <li><a href=\"signIn.php\" class=\"nav-link\">Sign In</a></li>\n";
echo "               </ul>\n";
echo "             </nav>\n";
echo "           </div>\n";
echo "            \n";
echo "         </div>\n";
echo "       </div>\n";
echo "      </header>\n";
echo "      \n";
echo "     <div class=\"hero inner-page\" style=\"background-image: url('images/background.jpeg');\">\n";
echo "       \n";
echo "       <div class=\"container\">\n";
echo "         <div class=\"row align-items-end \">\n";
echo "           <div class=\"col-lg-12\">\n";
echo "              <div class=\"intro\">\n";