

<!DOCTYPE html>
<html lang="en">

<?php
	//head
	include "head.php";
?>

<?php
		echo "<body onload=\"updateClock(); setInterval('updateClock()', 1000 )\">";
		
		//preloader
		include "preloader.php";
		//header
		include "headerWC.php";
		//nav
		include "nav.php";
		
?>

<?php
include 'header2.php';
print "                  <h1><strong>Buy bus ticket</strong> with just a few clicks.</h1>\n";
print "                </div>\n";
print "              </div>\n";
print "              \n";
print "              <form class=\"trip-form\" action=\"searchBus.php\" method=\"post\">\n";
print "                \n";
print "                <div class=\"row align-items-center\">\n";
print "                  \n";
print "                  <div class=\"mb-3 mb-md-0 col-md-3\">\n";
print "                    <select name=\"bus\" id=\"\" class=\"custom-select form-control\">\n";
print "                      <option value=\"rapid\">Rapid bus</option>\n";
print "                      <option value=\"aeroline\">Aeroline Malaysia Express Bus</option>\n";
print "                      <option value=\"nice\">NiCE Malaysia Express Bus</option>\n";
print "                      <option value=\"transtar\">Transtar Travel Malaysia Express Bus</option>\n";
print "                    </select>\n";
print "                  </div>\n";

print "                  <div class=\"mb-3 mb-md-0 col-md-3\">\n";
print "                    <select name=\"pick_up\" id=\"\" class=\"custom-select form-control\">\n";
print "                      <option value=\"\">Select Pick Up Point</option>\n";
print "                      <option value=\"penang\">Penang</option>\n";
print "                      <option value=\"kualaLumpur\">Kuala Lumpur</option>\n";
print "                      <option value=\"ipoh\">Ipoh</option>\n";
print "                      <option value=\"melaka\">Melaka</option>\n";
print "                      <option value=\"terengganu\">Terengganu</option>\n";
print "                      <option value=\"johor\">Johor</option>\n";
print "                      <option value=\"kelantan\">Kelantan</option>\n";
print "                      <option value=\"seremban\">Seremban</option>\n";
print "                      <option value=\"kedah\">Kedah</option>\n";
print "                      <option value=\"perlis\">Perlis</option>\n";

print "                    </select>\n";
print "                  </div>\n";

print "                  <div class=\"mb-3 mb-md-0 col-md-3\">\n";
print "                    <select name=\"destination\" id=\"\" class=\"custom-select form-control\">\n";
print "                      <option value=\"\">Select Destination</option>\n";
print "                      <option value=\"penang\">Penang</option>\n";
print "                      <option value=\"kualaLumpur\">Kuala Lumpur</option>\n";
print "                      <option value=\"ipoh\">Ipoh</option>\n";
print "                      <option value=\"melaka\">Melaka</option>\n";
print "                      <option value=\"terengganu\">Terengganu</option>\n";
print "                      <option value=\"johor\">Johor</option>\n";
print "                      <option value=\"kelantan\">Kelantan</option>\n";
print "                      <option value=\"seremban\">Seremban</option>\n";
print "                      <option value=\"kedah\">Kedah</option>\n";
print "                      <option value=\"perlis\">Perlis</option>\n";
print "                    </select>\n";
print "                  </div>\n";

print "                  <div class=\"mb-3 mb-md-0 col-md-3\">\n";
print "                    <div class=\"form-control-wrap\">\n";
print "                      <input type=\"text\" id=\"cf-3\" name=\"date\" placeholder=\"Pick up Date\" class=\"form-control datepicker px-3\">\n";
print "                      <span class=\"icon icon-date_range\"></span>\n";
print "\n";
print "                    </div>\n";
print "                  </div>\n";
echo"<br/>";

print "                  <div class=\"mb-3 mb-md-0 col-md-3\">\n";
print "                   <input type=\"submit\" value=\"Search Now\" class=\"btn btn-primary btn-block py-3\">\n";
print "                  </div>\n";
print "                </div>\n";
print "                \n";
print "              </form>\n";
print "\n";
print "            </div>\n";
print "          </div>\n";
print "        </div>\n";
print "      </div>\n";
print "  \n";
print "\n";
print "\n";
print "      <div class=\"site-section\">\n";
print "        <div class=\"container\">\n";
print "          <h2 class=\"section-heading\"><strong>How it works?</strong></h2>\n";
print "          <p class=\"mb-5\">Easy steps to get you started</p>    \n";
print "\n";
print "          <div class=\"row mb-5\">\n";
print "            <div class=\"col-lg-4 mb-4 mb-lg-0\">\n";
print "              <div class=\"step\">\n";
print "                <span>1</span>\n";
print "                <div class=\"step-inner\">\n";
print "                  <span class=\"number text-primary\">01.</span>\n";
print "                  <h3>Select a bus</h3>\n";
print "                  <p>Choose your desired bus!</p>\n";
print "                </div>\n";
print "              </div>\n";
print "            </div>\n";
print "            <div class=\"col-lg-4 mb-4 mb-lg-0\">\n";
print "              <div class=\"step\">\n";
print "                <span>2</span>\n";
print "                <div class=\"step-inner\">\n";
print "                  <span class=\"number text-primary\">02.</span>\n";
print "                  <h3>Fill up form</h3>\n";
print "                  <p>We will search for the bus that matches your requirements!</p>\n";
print "                </div>\n";
print "              </div>\n";
print "            </div>\n";
print "            <div class=\"col-lg-4 mb-4 mb-lg-0\">\n";
print "              <div class=\"step\">\n";
print "                <span>3</span>\n";
print "                <div class=\"step-inner\">\n";
print "                  <span class=\"number text-primary\">03.</span>\n";
print "                  <h3>Payment</h3>\n";
print "                  <p>Add the bus ticket to cart and check out!</p>\n";
print "                </div>\n";
print "              </div>\n";
print "            </div>\n";
print "          </div>\n";
print "          <div class=\"row\">\n";
print "            <div class=\"col-lg-4 mx-auto\">\n";
print "              <a href=\"#\" class=\"d-flex align-items-center play-now mx-auto\">\n";
print "                <span class=\"icon\">\n";
print "                  <span class=\"icon-play\"></span>\n";
print "                </span>\n";
print "                <span class=\"caption\">Video how it works</span>\n";
print "              </a>\n";
print "            </div>\n";
print "          </div>\n";
print "        </div>\n";
print "      </div>\n";
print "      \n";
print "      <div class=\"site-section\">\n";
print "        <div class=\"container\">\n";
print "          <div class=\"row align-items-center\">\n";
print "            <div class=\"col-lg-7 text-center order-lg-2\">\n";
print "              <div class=\"img-wrap-1 mb-5\">\n";
print "                <img src=\"images/buy_ticket_online.png\" alt=\"Image\" class=\"img-fluid\">\n";
print "              </div>\n";
print "            </div>\n";
print "            <div class=\"col-lg-4 ml-auto order-lg-1\">\n";
print "              <h3 class=\"mb-4 section-heading\"><strong>You can easily buy your own bus ticket here.</strong></h3>\n";
print "              <p class=\"mb-5\">We have helped more than 5000 Malaysians to buy bus ticket. Moreover, Malaysia government awarded us \"The most trustworthy online ticket booking website\" in 2016. We are very honoured for winning the award so please let us serve you! </p>\n";
print "              \n";
print "              <p><a href=\"purchase.php\" class=\"btn btn-primary\">Purchase bus ticket</a></p>\n";
print "            </div>\n";
print "          </div>\n";
print "        </div>\n";
print "      </div>\n";
print "\n";
print "      \n";
print "\n";
print "    <div class=\"site-section bg-light\">\n";
print "      <div class=\"container\">\n";
print "        <div class=\"row\">\n";
print "          <div class=\"col-lg-7\">\n";
print "            <h2 class=\"section-heading\"><strong>Type of Bus</strong></h2>\n";
print "            <p class=\"mb-5\">Buses that ticket is sold here:</p>    \n";
print "          </div>\n";
print "        </div>\n";
print "        \n";
print "\n";
print "        <div class=\"row\">\n";
print "          <div class=\"col-md-6 col-lg-4 mb-4\">\n";
print "\n";
print "            <div class=\"listing d-block  align-items-stretch\">\n";
print "              <div class=\"listing-img h-100 mr-4\">\n";
print "                <img src=\"images/rapid.jpg\" alt=\"Image\" class=\"img-fluid\">\n";
print "              </div>\n";
print "              <div class=\"listing-contents h-100\">\n";
print "                <h3>Rapid Bus</h3>\n";
print "                <div class=\"rent-price\">\n";
print "                  <strong>RM15.00</strong><span class=\"mx-1\">/</span>ticket\n";
print "                </div>\n";
print "                <div class=\"d-block d-md-flex mb-3 border-bottom pb-3\">\n";
print "                  <div class=\"listing-feature pr-4\">\n";
print "                    <span class=\"caption\">Luggage:</span>\n";
print "                    <span class=\"number\">20</span>\n";
print "                  </div>\n";
print "                  <div class=\"listing-feature pr-4\">\n";
print "                    <span class=\"caption\">Doors:</span>\n";
print "                    <span class=\"number\">4</span>\n";
print "                  </div>\n";
print "                  <div class=\"listing-feature pr-4\">\n";
print "                    <span class=\"caption\">Passenger:</span>\n";
print "                    <span class=\"number\">20</span>\n";
print "                  </div>\n";
print "                </div>\n";
print "                <div>\n";
print "                  <p>Rapid Bus is one of the most famous buses in Malaysia. They are just like their name, very rapid. </p>\n";
print "                  <p><a href=\"specificBus.php?name=rapid\" class=\"btn btn-primary btn-sm\">Buy ticket now</a></p>\n";
print "                </div>\n";
print "              </div>\n";
print "\n";
print "            </div>\n";
print "          </div>\n";
print "\n";
print "          <div class=\"col-md-6 col-lg-4 mb-4\">\n";
print "\n";
print "            <div class=\"listing d-block  align-items-stretch\">\n";
print "              <div class=\"listing-img h-100 mr-4\">\n";
print "                <img src=\"images/aeroline.jpg\" alt=\"Image\" class=\"img-fluid\">\n";
print "              </div>\n";
print "              <div class=\"listing-contents h-100\">\n";
print "                <h3>Aeroline Malaysia Express Bus</h3>\n";
print "                <div class=\"rent-price\">\n";
print "                  <strong>RM20.00</strong><span class=\"mx-1\">/</span>ticket\n";
print "                </div>\n";
print "                <div class=\"d-block d-md-flex mb-3 border-bottom pb-3\">\n";
print "                  <div class=\"listing-feature pr-4\">\n";
print "                    <span class=\"caption\">Luggage:</span>\n";
print "                    <span class=\"number\">25</span>\n";
print "                  </div>\n";
print "                  <div class=\"listing-feature pr-4\">\n";
print "                    <span class=\"caption\">Doors:</span>\n";
print "                    <span class=\"number\">2</span>\n";
print "                  </div>\n";
print "                  <div class=\"listing-feature pr-4\">\n";
print "                    <span class=\"caption\">Passenger:</span>\n";
print "                    <span class=\"number\">30</span>\n";
print "                  </div>\n";
print "                </div>\n";
print "                <div>\n";
print "                  <p>It is known as the most fabulous bus in Malaysia. The seat is extremely confortable, said by the passengers.</p>\n";
print "                  <p><a href=\"specificBus.php?name=aeroline\" class=\"btn btn-primary btn-sm\">Buy ticket now</a></p>\n";
print "                </div>\n";
print "              </div>\n";
print "\n";
print "            </div>\n";
print "          </div>\n";
print "          \n";
print "\n";
print "          <div class=\"col-md-6 col-lg-4 mb-4\">\n";
print "\n";
print "            <div class=\"listing d-block  align-items-stretch\">\n";
print "              <div class=\"listing-img h-100 mr-4\">\n";
print "                <img src=\"images/nice.jpg\" alt=\"Image\" class=\"img-fluid\">\n";
print "              </div>\n";
print "              <div class=\"listing-contents h-100\">\n";
print "                <h3>NiCE Malaysia Express Bus</h3>\n";
print "                <div class=\"rent-price\">\n";
print "                  <strong>RM10.00</strong><span class=\"mx-1\">/</span>ticket\n";
print "                </div>\n";
print "                <div class=\"d-block d-md-flex mb-3 border-bottom pb-3\">\n";
print "                  <div class=\"listing-feature pr-4\">\n";
print "                    <span class=\"caption\">Luggage:</span>\n";
print "                    <span class=\"number\">25</span>\n";
print "                  </div>\n";
print "                  <div class=\"listing-feature pr-4\">\n";
print "                    <span class=\"caption\">Doors:</span>\n";
print "                    <span class=\"number\">2</span>\n";
print "                  </div>\n";
print "                  <div class=\"listing-feature pr-4\">\n";
print "                    <span class=\"caption\">Passenger:</span>\n";
print "                    <span class=\"number\">30</span>\n";
print "                  </div>\n";
print "                </div>\n";
print "                <div>\n";
print "                  <p>It is a nice and confortable bus. It is favoured by Malaysians as the ticket price is cheap.</p>\n";
print "                  <p><a href=\"specificBus.php?name=nice\" class=\"btn btn-primary btn-sm\">Buy ticket now</a></p>\n";
print "                </div>\n";
print "              </div>\n";
print "\n";
print "            </div>\n";
print "          </div>\n";
print "\n";
print "          <div class=\"col-md-6 col-lg-4 mb-4\">\n";
print "\n";
print "            <div class=\"listing d-block  align-items-stretch\">\n";
print "              <div class=\"listing-img h-100 mr-4\">\n";
print "                <img src=\"images/transter.jpg\" alt=\"Image\" class=\"img-fluid\">\n";
print "              </div>\n";
print "              <div class=\"listing-contents h-100\">\n";
print "                <h3>Transtar Travel Malaysia Express Bus</h3>\n";
print "                <div class=\"rent-price\">\n";
print "                  <strong>RM20.00</strong><span class=\"mx-1\">/</span>ticket\n";
print "                </div>\n";
print "                <div class=\"d-block d-md-flex mb-3 border-bottom pb-3\">\n";
print "                  <div class=\"listing-feature pr-4\">\n";
print "                    <span class=\"caption\">Luggage:</span>\n";
print "                    <span class=\"number\">25</span>\n";
print "                  </div>\n";
print "                  <div class=\"listing-feature pr-4\">\n";
print "                    <span class=\"caption\">Doors:</span>\n";
print "                    <span class=\"number\">2</span>\n";
print "                  </div>\n";
print "                  <div class=\"listing-feature pr-4\">\n";
print "                    <span class=\"caption\">Passenger:</span>\n";
print "                    <span class=\"number\">30</span>\n";
print "                  </div>\n";
print "                </div>\n";
print "                <div>\n";
print "                  <p>One of the best buses in Malaysia. It has 10 years of history.</p>\n";
print "                  <p><a href=\"specificBus.php?name=transtar\" class=\"btn btn-primary btn-sm\">Buy ticket now</a></p>\n";
print "                </div>\n";
print "              </div>\n";
print "\n";
print "            </div>\n";
print "          </div>\n";
print "\n";

print "\n";
print "        </div>\n";
print "      </div>\n";
print "    </div>\n";
print "\n";
print "    <div class=\"site-section\">\n";
print "      <div class=\"container\">\n";
print "        <div class=\"row\">\n";
print "          <div class=\"col-lg-7\">\n";
print "            <h2 class=\"section-heading\"><strong>Features</strong></h2>\n";
print "            <p class=\"mb-5\">We have the features below:</p>    \n";
print "          </div>\n";
print "        </div>\n";
print "\n";
print "        <div class=\"row\">\n";
print "          <div class=\"col-lg-4 mb-5\">\n";
print "            <div class=\"service-1 dark\" style=\"background-color:#ffffff;height:320px\">\n";
print "              <span class=\"service-1-icon\">\n";
print "                <span class=\"icon-search\"></span>\n";
print "              </span>\n";
print "              <div class=\"service-1-contents\">\n";
print "                <h3>Search</h3>\n";
print "                <p>Click <a href=\"#\">here</a> to search for the bus you desired</p>\n";
print "                <p class=\"mb-0\"><a href=\"#\">Learn more</a></p>\n";
print "              </div>\n";
print "            </div>\n";
print "          </div>\n";
print "          <div class=\"col-lg-4 mb-5\">\n";
print "            <div class=\"service-1 dark\" style=\"background-color:#ffffff;height:320px\">\n";
print "              <span class=\"service-1-icon\">\n";
print "                <span class=\"icon-gear\"></span>\n";
print "              </span>\n";
print "              <div class=\"service-1-contents\">\n";
print "                <h3>Setting</h3>\n";
print "                <p>Click <a href=\"setting.php\">here</a> to change the setting.</p>\n";
print "                <p class=\"mb-0\"><a href=\"setting.php\">Learn more</a></p>\n";
print "              </div>\n";
print "            </div>\n";
print "          </div>\n";
print "          <div class=\"col-lg-4 mb-5\">\n";
print "            <div class=\"service-1 dark\" style=\"background-color:#ffffff;height:320px\">\n";
print "              <span class=\"service-1-icon\">\n";
print "                <span class=\"icon-credit-card\"></span>\n";
print "              </span>\n";
print "              <div class=\"service-1-contents\">\n";
print "                <h3>Purchase bus ticket</h3>\n";
print "                <p>Click <a href=\"purchase.php\">here</a> purchase bus ticket from us.</p>\n";
print "                <p class=\"mb-0\"><a href=\"purchase.php\">Learn more</a></p>\n";
print "              </div>\n";
print "            </div>\n";
print "          </div>\n";
print "\n";
print "          <div class=\"col-lg-4 mb-5\">\n";
print "            <div class=\"service-1 dark\" style=\"background-color:#ffffff;height:320px\">\n";
print "              <span class=\"service-1-icon\">\n";
print "                <span class=\"icon-calendar\"></span>\n";
print "              </span>\n";
print "              <div class=\"service-1-contents\">\n";
print "                <h3>Destinations and dates</h3>\n";
print "                <p>All the destinations, departure dates and arrival dates are listed <a href=\"purchase.php\">here</a>.</p>\n";
print "                <p class=\"mb-0\"><a href=\"purchase.php\">Learn more</a></p>\n";
print "              </div>\n";
print "            </div>\n";
print "          </div>\n";
print "          <div class=\"col-lg-4 mb-5\">\n";
print "            <div class=\"service-1 dark\" style=\"background-color:#ffffff;height:320px\">\n";
print "              <span class=\"service-1-icon\">\n";
print "                <span class=\"icon-bus\"></span>\n";
print "              </span>\n";
print "              <div class=\"service-1-contents\">\n";
print "                <h3>List of bus available</h3>\n";
print "                <p>Click <a href=\"listing.php\">here</a> to view all the buses available.</p>\n";
print "                <p class=\"mb-0\"><a href=\"listing.php\">Learn more</a></p>\n";
print "              </div>\n";
print "            </div>\n";
print "          </div>\n";
print "          <div class=\"col-lg-4 mb-5\">\n";
print "            <div class=\"service-1 dark\" style=\"background-color:#ffffff;height:320px\">\n";
print "              <span class=\"service-1-icon\">\n";
print "                <span class=\"icon-history\"></span>\n";
print "              </span>\n";
print "              <div class=\"service-1-contents\">\n";
print "                <h3>View purchase history</h3>\n";
print "                <p>Click <a href=\"history.php\">here</a> to view purchase history.</p>\n";
print "                <p class=\"mb-0\"><a href=\"history.php\">Learn more</a></p>\n";
print "              </div>\n";
print "            </div>\n";
print "          </div>\n";
print "\n";
print "        </div>\n";
print "      </div>\n";
print "    </div>\n";
print "\n";
print "    <div class=\"site-section bg-light\">\n";
print "      <div class=\"container\">\n";
print "        <div class=\"row\">\n";
print "          <div class=\"col-lg-7\">\n";
print "            <h2 class=\"section-heading\"><strong>Testimonials</strong></h2>\n";
print "            <p class=\"mb-5\">Some well-known people's comment on our website:</p>    \n";
print "          </div>\n";
print "        </div>\n";
print "        <div class=\"row\">\n";
print "          <div class=\"col-lg-4 mb-4 mb-lg-0\">\n";
print "            <div class=\"testimonial-2\">\n";
print "              <blockquote class=\"mb-4\">\n";
print "                <p>\"It is indeed a good website. The customer service is speedy and effective.\"</p>\n";
print "              </blockquote>\n";
print "              <div class=\"d-flex v-card align-items-center\">\n";
print "                <img src=\"images/person_1.jpg\" alt=\"Image\" class=\"img-fluid mr-3\">\n";
print "                <div class=\"author-name\">\n";
print "                  <span class=\"d-block\">Mike Fisher</span>\n";
print "                  <span>CEO of Sony</span>\n";
print "                </div>\n";
print "              </div>\n";
print "            </div>\n";
print "          </div>\n";
print "          <div class=\"col-lg-4 mb-4 mb-lg-0\">\n";
print "            <div class=\"testimonial-2\">\n";
print "              <blockquote class=\"mb-4\">\n";
print "                <p>\"An excellent website. I use it to buy bus ticket almost every day!\"</p>\n";
print "              </blockquote>\n";
print "              <div class=\"d-flex v-card align-items-center\">\n";
print "                <img src=\"images/person_2.jpg\" alt=\"Image\" class=\"img-fluid mr-3\">\n";
print "                <div class=\"author-name\">\n";
print "                  <span class=\"d-block\">Jean Stanley</span>\n";
print "                  <span>CEO of Apple</span>\n";
print "                </div>\n";
print "              </div>\n";
print "            </div>\n";
print "          </div>\n";
print "          <div class=\"col-lg-4 mb-4 mb-lg-0\">\n";
print "            <div class=\"testimonial-2\">\n";
print "              <blockquote class=\"mb-4\">\n";
print "                <p>\"Very useful website! It makes my life easier!\"</p>\n";
print "              </blockquote>\n";
print "              <div class=\"d-flex v-card align-items-center\">\n";
print "                <img src=\"images/person_3.jpg\" alt=\"Image\" class=\"img-fluid mr-3\">\n";
print "                <div class=\"author-name\">\n";
print "                  <span class=\"d-block\">Katie Rose</span>\n";
print "                  <span >Prime Minister of Malaysia</span>\n";
print "                </div>\n";
print "              </div>\n";
print "            </div>\n";
print "          </div>\n";
print "        </div>\n";
print "      </div>\n";
print "    </div>\n";
print "\n";
include 'footer1.php';
print "  </body>\n";
print "\n";
print "</html>\n";

?>

<?php
	include "jsscripts.php";
	//back to top button
	include "btn_backtotop.php";
?>


